### ISSUE TITLE
python 3 support please

### ISSUE THREAD

**Issue by pythonmobile** [100/Solid#6]

**Comment by Donal-Flanagan** [comment]
Version 0.11 is not available via pip. Do you have any plans to update the code to python3 and make it available?

**Comment by ajasja** [comment]
This is a very elegant framework! @100  do you still have plans to maintain it and port it to python 3?

**Comment by torressa** [comment]
@ajasja It works on python 3

**Comment by ajasja** [comment]
@torressa Thank you it does indeed!
(somebody should close the issue:)

**Comment by pythonmobile** [comment]
Thanks!
